name: Release Build

on:
  push:
    tags:
      - 'v*.*.*'

env:
  APP_NAME: "Test Case"
  APP_VERSION: ${{ github.ref_name }}

jobs:
  # 1. 创建 Release
  create-release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create.outputs.upload_url }}
      release_id: ${{ steps.create.outputs.id }}
    steps:
      - uses: actions/checkout@v4

      - name: Generate release notes and release.txt
        id: release_notes
        run: |
          # 提取版本信息
          VERSION=${{ github.ref_name }}
          CLEAN_VERSION=${VERSION#v}
          DOWNLOAD_BASE_URL="https://github.com/${{ github.repository }}/releases/download/$VERSION"
          
          # 生成release.txt
          cat > release.txt <<EOF
          Release $VERSION
          ==================

          Download Links:

          ### Windows
          - [x86_64]($DOWNLOAD_BASE_URL/$APP_NAME_$VERSION_x86_64.exe)
          - [ARM64]($DOWNLOAD_BASE_URL/$APP_NAME-$VERSION-arm64.exe)
          
          ### macOS
          - [x86_64 (Intel)]($DOWNLOAD_BASE_URL/$APP_NAME-$VERSION-x86_64.dmg)
          - [aarch64 (Apple Silicon)]($DOWNLOAD_BASE_URL/$APP_NAME-$VERSION-aarch64.dmg)
          
          ### Linux
          - [x86_64]($DOWNLOAD_BASE_URL/$APP_NAME-$VERSION-x86_64.deb)
          - [ARM64]($DOWNLOAD_BASE_URL/$APP_NAME-$VERSION-arm64.deb)
          EOF
          
          # 生成发布说明（包含变更日志）
          echo "RELEASE_NOTES<<EOF" >> $GITHUB_ENV
          echo "# Release $VERSION" >> $GITHUB_ENV
          echo "" >> $GITHUB_ENV
          echo "## Changelog" >> $GITHUB_ENV
          echo "" >> $GITHUB_ENV
          # 获取当前标签与上一个标签之间的提交记录
          git log --pretty=format:"- %s" $(git describe --tags --abbrev=0 HEAD^)..HEAD >> $GITHUB_ENV
          echo "" >> $GITHUB_ENV
          echo "## Download Links" >> $GITHUB_ENV
          echo "" >> $GITHUB_ENV
          cat release.txt | grep -v "==================" >> $GITHUB_ENV  # 避免重复标题线
          echo "EOF" >> $GITHUB_ENV

      - name: Create GitHub Release
        id: create
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"
          body: ${{ env.RELEASE_NOTES }}
          draft: false
          prerelease: false
          fail_on_unmatched_files: false
          files: |
            release.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # 2. 多平台构建
  build:
    needs: create-release
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          # Windows 平台
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            platform_key: windows-x86_64
            filename_suffix: x86_64.exe
            package_type: exe
          - os: windows-latest
            target: aarch64-pc-windows-msvc
            platform_key: windows-aarch64
            filename_suffix: arm64.exe
            package_type: exe

          # macOS 平台
          - os: macos-latest
            target: aarch64-apple-darwin
            platform_key: darwin-aarch64
            filename_suffix: aarch64.dmg
            package_type: dmg
          - os: macos-latest
            target: x86_64-apple-darwin
            platform_key: darwin-x86_64
            filename_suffix: x86_64.dmg
            package_type: dmg

          # Linux DEB 包
          - os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
            platform_key: linux-x86_64
            filename_suffix: x86_64.deb
            package_type: deb

          # Linux RPM 包
          - os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
            platform_key: linux-x86_64
            filename_suffix: x86_64.rpm
            package_type: rpm

    runs-on: ${{ matrix.os }}
    steps:
      # 检出代码
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 安装 Rust 稳定版本
      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@stable

      # 添加 Rust 目标架构
      - name: Add Rust Target
        run: rustup target add ${{ matrix.target }}

      # 配置 Rust 缓存
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: src-tauri
          save-if: false
      
      # 安装依赖（仅在 Ubuntu 上）
      - name: Install dependencies (ubuntu only)
        if: matrix.os == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libxslt1.1 libwebkit2gtk-4.1-dev libayatana-appindicator3-dev librsvg2-dev patchelf
          
      # 安装 x86 OpenSSL (macOS only)
      - name: Install x86 OpenSSL (macOS only)
        if: matrix.target == 'x86_64-apple-darwin'
        run: |
          arch -x86_64 brew install openssl@3
          echo "OPENSSL_DIR=$(brew --prefix openssl@3)" >> $GITHUB_ENV
          echo "OPENSSL_INCLUDE_DIR=$(brew --prefix openssl@3)/include" >> $GITHUB_ENV
          echo "OPENSSL_LIB_DIR=$(brew --prefix openssl@3)/lib" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=$(brew --prefix openssl@3)/lib/pkgconfig" >> $GITHUB_ENV
      
      # 安装 Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      # 安装 pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          
      # 安装依赖
      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile
          pnpm list
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"

      # 构建 Tauri 应用
      - name: Tauri build
        id: tauri_build
        uses: tauri-apps/tauri-action@v0
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # 配置 Tauri 签名密钥
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          # 配置 Tauri 签名密钥密码
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          tagName: ${{ github.ref_name }} # 发布标签名
          prerelease: false
          args: --target ${{ matrix.target }}
          includeUpdaterJson: true
          artifactName: "${{ github.ref_name }}-${{ matrix.filename_suffix }}"

      # 保存构建产物信息
      - name: Save build artifacts info
        id: artifacts_info
        run: |
          # 解析 tauri_build 输出的 artifactInfo（包含 URL、签名等）
          ARTIFACT_INFO='${{ steps.tauri_build.outputs.artifactInfo }}'
          echo "Artifact Info: $ARTIFACT_INFO"

          # 提取关键信息（使用 jq 解析 JSON，需先安装 jq）
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            # Windows 安装 jq
            choco install jq -y
            JQ_PATH="C:\ProgramData\chocolatey\bin\jq.exe"
          else
            # macOS/Linux 已预装 jq
            JQ_PATH="jq"
          fi

          # 提取 URL、签名、文件名
          DOWNLOAD_URL=$($JQ_PATH -r '.url' <<< "$ARTIFACT_INFO")
          SIGNATURE=$($JQ_PATH -r '.signature' <<< "$ARTIFACT_INFO")
          FILENAME=$($JQ_PATH -r '.name' <<< "$ARTIFACT_INFO")

          # 去除版本前缀 v（如 v1.0.0 → 1.0.0）
          CLEAN_VERSION=${{ github.ref_name }}
          CLEAN_VERSION=${CLEAN_VERSION#v}

          # 生成当前平台的 JSON 片段（用于后续汇总）
          echo "{
            \"${{ matrix.platform_key }}\": {
              \"url\": \"$DOWNLOAD_URL\",
              \"signature\": \"$SIGNATURE\",
              \"version\": \"$CLEAN_VERSION\",
              \"filename\": \"$FILENAME\"
            }
          }" > platform_${{ matrix.platform_key }}_${{ matrix.package_type }}.json

          # 输出路径供后续步骤使用
          echo "PLATFORM_JSON_PATH=platform_${{ matrix.platform_key }}_${{ matrix.package_type }}.json" >> $GITHUB_OUTPUT

      # 上传平台特定的JSON文件
      - name: Upload platform JSON
         uses: actions/upload-artifact@v4
        with:
          name: platform-json-fragments
          path: ${{ steps.artifacts_info.outputs.PLATFORM_JSON_PATH }}
          retention-days: 1  # 仅保留1天，避免占用空间

  # 3. 生成并上传latest.json
  generate-latest-json:
    needs: [create-release, build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Download all platform JSONs
        uses: actions/download-artifact@v4
        with:
          name: platform-jsons
          path: ./platforms
          
      - name: Generate latest.json
        run: |
          # 提取版本号（去掉v前缀）
          VERSION=$(echo ${{ github.ref_name }} | sed 's/^v//')
          
          # 获取发布说明
          NOTES=$(cat << 'EOF'
          本次更新包含多项改进和bug修复，提升了应用的稳定性和用户体验。
          详细更新内容请查看完整的发布说明。
          EOF
          )
          
          # 格式化发布说明
          NOTES=$(echo "$NOTES" | sed ':a;N;$!ba;s/\n/\\n/g')
          
          # 创建latest.json文件
          echo "{" > latest.json
          echo "  \"version\": \"$VERSION\"," >> latest.json
          echo "  \"notes\": \"$NOTES\"," >> latest.json
          echo "  \"pub_date\": \"$(date -u +"%Y-%m-%dT%H:%M:%SZ")\"," >> latest.json
          echo "  \"platforms\": {" >> latest.json
          
          # 合并所有平台的JSON片段
          FIRST=true
          for file in ./platforms/*.json; do
            if [ "$FIRST" = true ]; then
              FIRST=false
            else
              echo "," >> latest.json
            fi
            cat "$file" >> latest.json
          done
          
          echo "  }" >> latest.json
          echo "}" >> latest.json
          
          # 显示生成的latest.json内容
          cat latest.json
          
      - name: Upload latest.json to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: latest.json
          append_body: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
